# Generated by Django 5.1.3 on 2024-12-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_remove_request_accepted_by_request_accepted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, default='No address provided', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='latitude',
            field=models.FloatField(blank=True, default=51.99656842422461, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='location_type',
            field=models.CharField(choices=[('address', 'Address'), ('coordinates', 'Latitude and Longitude')], default='address', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='longitude',
            field=models.FloatField(blank=True, default=-0.9913942306871908, null=True),
        ),
    ]
