# Generated by Django 5.1.3 on 2024-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_latitude_alter_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='No address provided', max_length=255),
        ),
    ]
