# Generated by Django 5.1.3 on 2024-12-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_type',
            field=models.CharField(choices=[('address', 'Address'), ('coordinates', 'Latitude and Longitude')], default='address', max_length=20),
        ),
    ]
