# Generated by Django 5.1.3 on 2024-12-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='location',
        ),
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, default='No address provided', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='location_type',
            field=models.CharField(choices=[('address', 'Address'), ('coordinates', 'Latitude and Longitude')], default='address', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
